apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    name: postgresql
spec:
  type: NodePort
  ports:
    - port: {{ .Values.database.port }}
      nodePort: {{ .Values.database.nodePort }}
      name: http
  selector:
    name: postgresql