apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}
spec:
  ipFamily: IPv6
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      name: http
      targetPort: {{ .Values.service.targetPort }}
  externalIPs:
    - {{ .Values.service.external.ip }}
  selector:
    app: {{ include "fullname" . }}